### ISSUE TITLE
ERROR: bucket overflow

### ISSUE THREAD

**Issue by victoryc** [mit-han-lab/torchsparse#55]
I occasionally get the following error for the code that normally works. Any idea what causes this error? 

```
526/512 ERROR: bucket overflow! (n=823, bucket_num=2/4, key=0)
512/512 ERROR: bucket overflow! (n=823, bucket_num=2/4, key=0)
514/512 ERROR: bucket overflow! (n=823, bucket_num=2/4, key=0)
516/512 ERROR: bucket overflow! (n=823, bucket_num=2/4, key=0)
528/512 ERROR: bucket overflow! (n=823, bucket_num=2/4, key=0)
530/512 ERROR: bucket overflow! (n=823, bucket_num=2/4, key=0)
...
```

An observation that may or may not be relevant: I noticed that this error seems to occur when the number of coordinates in the sparse tensor is small. The same code ran fine without producing the above error when a bigger input with more coordinates was fed.

**Comment by zhijian-liu** [comment]
Could you provide us with a sample code and data that can reproduce this error? Thanks!

**Comment by victoryc** [comment]
As of now, my program is quite big (involving multiple files) and the error occurs only occasionally. So, I am not in a position to provide simple sample code to reproduce this as of now. Let me try investigating this and see whether I can narrow it down. 

As of now, if anybody has any insights about what could potentially cause those errors, that can help my investigation. 
Thanks.

**Comment by victoryc** [comment]
I found out the limitation in the code that is causing this. 
In query.cpp, the following line is used to compute the size of the table:
`int table_size =  2 * pow(2,ceil(log2((double)n)));`
In hashmap.cuh, the number of buckets is computed to be table_size/BUCKET_SIZE, where BUCKET_SIZE is 512.

When the hash values of the coordinates are very distributed there is no problem. Taking the table_size to be 2 times next power of 2 greater than n, as done in the line above provides some amount of tolerance for the case where the hash values are not evenly distributed. But, that is only a heuristic. When the hash values are more un-evenly distributed than that, the code fails with the "ERROR: bucket overflow!" messages.

I was able to avoid the error in my specific case by changing "table_size = 2 * blah" to "table_size = 3 * blah". But, of course this is not a real solution of course. It is just a hack that increases the tolerance for unevenness some more.

**Comment by victoryc** [comment]
For the benefit of others running into this, let me mention how I addressed it for now. There used to be the following line in query.cpp:
`int table_size = 2 * pow(2,ceil(log2((double)n)));`
I replaced it by:
```
  const int nextPow2 = pow(2,ceil(log2((double)n)));
  // When n is large, the hash values tend to be more evenly distrubuted and choosing table_size to be 
  // 2 * nextPow2 typically suffices. For smaller n, the effect of uneven distribution of hash values is more
  // pronounced and hence we choose table_size to be 4 * nextPow2 to reduce the chance of bucket overflow.
  int table_size =  (n < 2048) ? 4 * nextPow2 : 2 * nextPow2;
```
This way, for larger n, when memory size consideration is more important, the table_size is getting computed to be the same as it used to be. For smaller n, when the effect of uneven distribution of hash values is more pronounced and memory size consideration is not as important, we compute the table_size to be bigger than it used to be, to reduce the chances of bucket overflow error.

Original authors: I will submit a pull request with this change. But, I won't be offended :-) if you reject this pull request since this change just reduces the chances of the bucket overflow error and doesn't address the issue in a robust, thorough way.

**Comment by zhijian-liu** [comment]
@victoryc, thank you so much for investigating this issue! I was discussing with @kentangSJTU this morning about the same solution. I will be happy to take a look after you submit the PR. We are also thinking about making this a knob to tune so that users can change that based on their needs. Take one step further, it might also be possible to dynamically adjust this if there is overflow.

**Comment by harry1576** [comment]
Hi there, 
I am getting the same error. Are you still planning on adding a knob to tune?
Cheers,
Harry

**Comment by zhijian-liu** [comment]
Hi @harry1576, it's not in our plan for the near future. As a workaround, you may follow https://github.com/mit-han-lab/torchsparse/issues/55#issuecomment-815981257 to enlarge the table size further.

**Comment by Akola-Mbey-Denis** [comment]
Please I followed through the suggestions for this issue, but that did not fix it.  Is there an alternative solution to this problem.

**Comment by LianMing345** [comment]
Hello, may I ask where the location of the query.cpp file you mentioned is?Do you have a new solution?

**Comment by LianMing345** [comment]
> For the benefit of others running into this, let me mention how I addressed it for now. There used to be the following line in query.cpp: `int table_size = 2 * pow(2,ceil(log2((double)n)));` I replaced it by:
> 
> ```
>   const int nextPow2 = pow(2,ceil(log2((double)n)));
>   // When n is large, the hash values tend to be more evenly distrubuted and choosing table_size to be 
>   // 2 * nextPow2 typically suffices. For smaller n, the effect of uneven distribution of hash values is more
>   // pronounced and hence we choose table_size to be 4 * nextPow2 to reduce the chance of bucket overflow.
>   int table_size =  (n < 2048) ? 4 * nextPow2 : 2 * nextPow2;
> ```
> 
> This way, for larger n, when memory size consideration is more important, the table_size is getting computed to be the same as it used to be. For smaller n, when the effect of uneven distribution of hash values is more pronounced and memory size consideration is not as important, we compute the table_size to be bigger than it used to be, to reduce the chances of bucket overflow error.
> 
> Original authors: I will submit a pull request with this change. But, I won't be offended :-) if you reject this pull request since this change just reduces the chances of the bucket overflow error and doesn't address the issue in a robust, thorough way.

Hello, may I ask where the location of the query.cpp file you mentioned is?Do you have a new solution?
